spring:
  application:
    name: hub-service

  data:
    redis:
      host: ENC(WCP+8mkysXzEV+eZ1E5A9+XQsysXwDwz)
      port: 16371
      username: ENC(hK+1LVIhvsPYxTR80FgHp15Fhz64VZWX)
      password: ENC(hK+1LVIhvsPYxTR80FgHp15Fhz64VZWX)

  datasource:
    url: ENC(w/qxsogEfvgBRSPgkV068Bv4ys0L0DrQ9z/DSlc8/J5ExaZoFPTkoattvgqf5b6f)
    username: ENC(O0JZhVcB3wpGWRMG9nvHVgGq6/kWnWpc)
    password: ENC(XSH/orVzAokrfuvimJvFnA==)
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data_sql.sql

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    enabled: true
    path: /docs
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    enabled: true
    path: /api-docs-hub-service