spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 서비스 디스커버리로 동적 라우트 생성
      auth:
        login:
          endpoint: /api/v1/auth/login
        signup:
          endpoint: /api/v1/auth/signup
        base:
          url: http://localhost:18081
        validate:
          endpoint: /gateway/v1/auth/validate
        secret:
          key: ENC(HI4A/uV5RCH/wOUjxaZDApv6DlH9ANhHYK87ojAyzTI=)
      routes:
        - id: auth-service # 인증 서비스
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**, /api-docs-auth-service

        - id: user-service # 사용자 서비스
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**, /api-docs-user-service

        - id: delivery-manager-service # 배송 담당자 서비스
          uri: lb://delivery-manager-service
          predicates:
            - Path=/api/v1/delivery-managers/**, /api-docs-delivery-manager-service

        - id: order-service # 주문 서비스
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**, /api-docs-order-service

        - id: delivery-service # 배송 서비스
          uri: lb://delivery-service
          predicates:
            - Path=/api/v1/delivery/**, /api-docs-delivery-service

        - id: company-service # 업체 서비스
          uri: lb://company-service
          predicates:
            - Path=/api/v1/company/**, /api-docs-company-service

        - id: product-service # 상품 서비스
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**, /api-docs-product-service

        - id: hub-service # 허브 서비스
          uri: lb://hub-service
          predicates:
            - Path=/api/v1/hubs/**, /api-docs-hub-service

        - id: hub-transit-route-service # 허브 간 이동 정보 서비스
          uri: lb://hub-transit-route-service
          predicates:
            - Path=/api/v1/hub-transit/route/**, /api-docs-hub-transit-route-service

        - id: slack-service # 슬랙 서비스
          uri: lb://slack-service
          predicates:
            - Path=/api/v1/slack/**, /api-docs-slack-service

        - id: ai-service # AI 서비스
          uri: lb://ai-service
          predicates:
            - Path=/api/v1/ai/**, /api-docs-ai-service

        - id: map-service # 지도 서비스
          uri: lb://map-service
          predicates:
            - Path=/api/v1/maps/**, /api-docs-map-service
springdoc:
  swagger-ui:
    enabled: true
    path: /docs
    urls:
      - name: auth-service
        url: /api-docs-auth-service
      - name: user-service
        url: /api-docs-user-service
      - name: delivery-manager-service
        url: /api-docs-delivery-manager-service
      - name: order-service
        url: /api-docs-order-service
      - name: delivery-service
        url: /api-docs-delivery-service
      - name: company-service
        url: /api-docs-company-service
      - name: product-service
        url: /api-docs-product-service
      - name: hub-service
        url: /api-docs-hub-service
      - name: hub-route-service
        url: /api-docs-hub-route-service
      - name: slack-service
        url: /api-docs-slack-service
      - name: ai-service
        url: /api-docs-ai-service
      - name: map-service
        url: /api-docs-map-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  tracing:
    sampling:
      probability: 0.1  # 10% of the requests will be traced
    enabled: true  # Enable tracing

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans  # Zipkin server URL for receiving spans
      connect-timeout: 1s  # Timeout for connecting to Zipkin server
      encoding: json  # The format of the trace data (you can use json or protobuf)
      read-timeout: 10s  # Timeout for reading from the Zipkin server

